package com.example.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.example.domain.Users;
import com.example.domain.UsersExample;

public interface UsersMapper {
	@Select({
	    "select * from users where id = #{id} limit 1"
	})
	Users selectById(int id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	long countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	int deleteByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	@Insert({ "insert into users (USER, CURRENT_CONNECTIONS, ", "TOTAL_CONNECTIONS)",
			"values (#{user,jdbcType=CHAR}, #{currentConnections,jdbcType=BIGINT}, ",
			"#{totalConnections,jdbcType=BIGINT})" })
	int insert(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	int insertSelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);
}