package com.example.domain;

import java.util.Date;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.USER
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	private String user;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.CURRENT_CONNECTIONS
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	private Long currentConnections;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.TOTAL_CONNECTIONS
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	private Long totalConnections;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.USER
	 * @return  the value of users.USER
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.USER
	 * @param user  the value for users.USER
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	public void setUser(String user) {
		this.user = user == null ? null : user.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.CURRENT_CONNECTIONS
	 * @return  the value of users.CURRENT_CONNECTIONS
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	public Long getCurrentConnections() {
		return currentConnections;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.CURRENT_CONNECTIONS
	 * @param currentConnections  the value for users.CURRENT_CONNECTIONS
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	public void setCurrentConnections(Long currentConnections) {
		this.currentConnections = currentConnections;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.TOTAL_CONNECTIONS
	 * @return  the value of users.TOTAL_CONNECTIONS
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	public Long getTotalConnections() {
		return totalConnections;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.TOTAL_CONNECTIONS
	 * @param totalConnections  the value for users.TOTAL_CONNECTIONS
	 * @mbg.generated  Mon Mar 15 16:34:16 JST 2021
	 */
	public void setTotalConnections(Long totalConnections) {
		this.totalConnections = totalConnections;
	}
}